
<?php

$cadenaTablaRecibidos = "";
$aumento = 79;
$background = "";
$ind = $this->indicadores;
for($iTabla = 0; $iTabla <= 23; $iTabla++) {
	if($iTabla >= 22){$background = "background-color:#393641;color:#fefefe";}
	   $cadenaTablaRecibidos.= "<p onclick=\"abrirAsuntos('".$this->anio."','".$this->idArea."','".$this->idUsuario."','".$this->opcion."','".$ind[$iTabla]->getEje()."');\" style='top:".$aumento."px;left:".$this->size."px;".$background."' class='ejeColor".$ind[$iTabla]->getEje()." ejesCuadricula p".$iTabla.$this->aux."'>".$ind[$iTabla]->getTotal()."</p>";
	$aumento += 26.5;
}
echo $cadenaTablaRecibidos;

?>
<script>
$(document).ready(function(){


  
  $(".p0r,.p1r").on("click",function()
  {
	 
	$("p.nEje1").css("background-color", "#5d2852");
	$(".p0r").css("background-color", "#5d2852");
	$(".p0r").css("color", "#fefefe");
	$(".p1r").css("background-color", "#5d2852");
	$(".p1r").css("color", "#fefefe");
	$(".p0e").css("background-color", "#5d2852");
	$(".p0e").css("color", "#fefefe");
	$(".p1e").css("background-color", "#5d2852");
	$(".p1e").css("color", "#fefefe");
	$(".p0o").css("background-color", "#5d2852");
	$(".p0o").css("color", "#fefefe");
	$(".p1o").css("background-color", "#5d2852");
	$(".p1o").css("color", "#fefefe");
	$(".franja").css("height", "116px");
	
	$("p.nEje2").css("background-color", "#4d4d57");
	$("p.nEje3").css("background-color", "#4d4d57");
	$("p.nEje4").css("background-color", "#4d4d57");
	$("p.nEje5").css("background-color", "#4d4d57");
	$("p.nEje6").css("background-color", "#4d4d57");
	$("p.nEje7").css("background-color", "#4d4d57");
	$("p.nEje8").css("background-color", "#4d4d57");
	$("p.nEje9").css("background-color", "#4d4d57");
	$("p.nEje10").css("background-color", "#4d4d57");
	$("p.nEje11").css("background-color", "#4d4d57");
	
	$(".p2r").css("background-color", "#a9a9ae");
	$(".p2r").css("color", "#000");
	$(".p3r").css("background-color", "#a9a9ae");
	$(".p3r").css("color", "#000");
	$(".p2e").css("background-color", "#a9a9ae");
	$(".p2e").css("color", "#000");
	$(".p3e").css("background-color", "#a9a9ae");
	$(".p3e").css("color", "#000");
	$(".p2o").css("background-color", "#a9a9ae");
	$(".p2o").css("color", "#000");
	$(".p3o").css("background-color", "#a9a9ae");
	$(".p3o").css("color", "#000");
	
	$(".p4r").css("background-color", "#a9a9ae");
	$(".p4r").css("color", "#000");
	$(".p5r").css("background-color", "#a9a9ae");
	$(".p5r").css("color", "#000");
	$(".p4e").css("background-color", "#a9a9ae");
	$(".p4e").css("color", "#000");
	$(".p5e").css("background-color", "#a9a9ae");
	$(".p5e").css("color", "#000");
	$(".p4o").css("background-color", "#a9a9ae");
	$(".p4o").css("color", "#000");
	$(".p5o").css("background-color", "#a9a9ae");
	$(".p5o").css("color", "#000");
	
	$(".p6r").css("background-color", "#a9a9ae");
	$(".p6r").css("color", "#000");
	$(".p7r").css("background-color", "#a9a9ae");
	$(".p7r").css("color", "#000");
	$(".p6e").css("background-color", "#a9a9ae");
	$(".p6e").css("color", "#000");
	$(".p7e").css("background-color", "#a9a9ae");
	$(".p7e").css("color", "#000");
	$(".p6o").css("background-color", "#a9a9ae");
	$(".p6o").css("color", "#000");
	$(".p7o").css("background-color", "#a9a9ae");
	$(".p7o").css("color", "#000");
	
	$(".p8r").css("background-color", "#a9a9ae");
	$(".p8r").css("color", "#000");
	$(".p9r").css("background-color", "#a9a9ae");
	$(".p9r").css("color", "#000");
	$(".p8e").css("background-color", "#a9a9ae");
	$(".p8e").css("color", "#000");
	$(".p9e").css("background-color", "#a9a9ae");
	$(".p9e").css("color", "#000");
	$(".p8o").css("background-color", "#a9a9ae");
	$(".p8o").css("color", "#000");
	$(".p9o").css("background-color", "#a9a9ae");
	$(".p9o").css("color", "#000");
	
	$(".p10r").css("background-color", "#a9a9ae");
	$(".p10r").css("color", "#000");
	$(".p11r").css("background-color", "#a9a9ae");
	$(".p11r").css("color", "#000");
	$(".p10e").css("background-color", "#a9a9ae");
	$(".p10e").css("color", "#000");
	$(".p11e").css("background-color", "#a9a9ae");
	$(".p11e").css("color", "#000");
	$(".p10o").css("background-color", "#a9a9ae");
	$(".p10o").css("color", "#000");
	$(".p11o").css("background-color", "#a9a9ae");
	$(".p11o").css("color", "#000");
	
	$(".p12r").css("background-color", "#a9a9ae");
	$(".p12r").css("color", "#000");
	$(".p13r").css("background-color", "#a9a9ae");
	$(".p13r").css("color", "#000");
	$(".p12e").css("background-color", "#a9a9ae");
	$(".p12e").css("color", "#000");
	$(".p13e").css("background-color", "#a9a9ae");
	$(".p13e").css("color", "#000");
	$(".p12o").css("background-color", "#a9a9ae");
	$(".p12o").css("color", "#000");
	$(".p13o").css("background-color", "#a9a9ae");
	$(".p13o").css("color", "#000");
	
	$(".p14r").css("background-color", "#a9a9ae");
	$(".p14r").css("color", "#000");
	$(".p15r").css("background-color", "#a9a9ae");
	$(".p15r").css("color", "#000");
	$(".p14e").css("background-color", "#a9a9ae");
	$(".p14e").css("color", "#000");
	$(".p15e").css("background-color", "#a9a9ae");
	$(".p15e").css("color", "#000");
	$(".p14o").css("background-color", "#a9a9ae");
	$(".p14o").css("color", "#000");
	$(".p15o").css("background-color", "#a9a9ae");
	$(".p15o").css("color", "#000");
	
	$(".p16r").css("background-color", "#a9a9ae");
	$(".p16r").css("color", "#000");
	$(".p17r").css("background-color", "#a9a9ae");
	$(".p17r").css("color", "#000");
	$(".p16e").css("background-color", "#a9a9ae");
	$(".p16e").css("color", "#000");
	$(".p17e").css("background-color", "#a9a9ae");
	$(".p17e").css("color", "#000");
	$(".p16o").css("background-color", "#a9a9ae");
	$(".p16o").css("color", "#000");
	$(".p17o").css("background-color", "#a9a9ae");
	$(".p17o").css("color", "#000");
	
	$(".p18r").css("background-color", "#a9a9ae");
	$(".p18r").css("color", "#000");
	$(".p19r").css("background-color", "#a9a9ae");
	$(".p19r").css("color", "#000");
	$(".p18e").css("background-color", "#a9a9ae");
	$(".p18e").css("color", "#000");
	$(".p19e").css("background-color", "#a9a9ae");
	$(".p19e").css("color", "#000");
	$(".p18o").css("background-color", "#a9a9ae");
	$(".p18o").css("color", "#000");
	$(".p19o").css("background-color", "#a9a9ae");
	$(".p19o").css("color", "#000");
	
	$(".p20r").css("background-color", "#a9a9ae");
	$(".p20r").css("color", "#000");
	$(".p21r").css("background-color", "#a9a9ae");
	$(".p21r").css("color", "#000");
	$(".p20e").css("background-color", "#a9a9ae");
	$(".p20e").css("color", "#000");
	$(".p21e").css("background-color", "#a9a9ae");
	$(".p21e").css("color", "#000");
	$(".p20o").css("background-color", "#a9a9ae");
	$(".p20o").css("color", "#000");
	$(".p21o").css("background-color", "#a9a9ae");
	$(".p21o").css("color", "#000");
	
	
  });
  
  
  
  $(".p2r,.p3r").click(function()
  {
	$("p.nEje2").css("background-color", "#5d2852");
	$(".p2r").css("background-color", "#5d2852");
	$(".p2r").css("color", "#fefefe");
	$(".p3r").css("background-color", "#5d2852");
	$(".p3r").css("color", "#fefefe");
	$(".p2e").css("background-color", "#5d2852");
	$(".p2e").css("color", "#fefefe");
	$(".p3e").css("background-color", "#5d2852");
	$(".p3e").css("color", "#fefefe");
	$(".p2o").css("background-color", "#5d2852");
	$(".p2o").css("color", "#fefefe");
	$(".p3o").css("background-color", "#5d2852");
	$(".p3o").css("color", "#fefefe");
	$(".franja").css("height", "170px");
	
	$("p.nEje1").css("background-color", "#4d4d57");
	$("p.nEje3").css("background-color", "#4d4d57");
	$("p.nEje4").css("background-color", "#4d4d57");
	$("p.nEje5").css("background-color", "#4d4d57");
	$("p.nEje6").css("background-color", "#4d4d57");
	$("p.nEje7").css("background-color", "#4d4d57");
	$("p.nEje8").css("background-color", "#4d4d57");
	$("p.nEje9").css("background-color", "#4d4d57");
	$("p.nEje10").css("background-color", "#4d4d57");
	$("p.nEje11").css("background-color", "#4d4d57");
	
	$(".p0r").css("background-color", "#a9a9ae");
	$(".p0r").css("color", "#000");
	$(".p1r").css("background-color", "#a9a9ae");
	$(".p1r").css("color", "#000");
	$(".p0e").css("background-color", "#a9a9ae");
	$(".p0e").css("color", "#000");
	$(".p1e").css("background-color", "#a9a9ae");
	$(".p1e").css("color", "#000");
	$(".p0o").css("background-color", "#a9a9ae");
	$(".p0o").css("color", "#000");
	$(".p1o").css("background-color", "#a9a9ae");
	$(".p1o").css("color", "#000");
	
	$(".p4r").css("background-color", "#a9a9ae");
	$(".p4r").css("color", "#000");
	$(".p5r").css("background-color", "#a9a9ae");
	$(".p5r").css("color", "#000");
	$(".p4e").css("background-color", "#a9a9ae");
	$(".p4e").css("color", "#000");
	$(".p5e").css("background-color", "#a9a9ae");
	$(".p5e").css("color", "#000");
	$(".p4o").css("background-color", "#a9a9ae");
	$(".p4o").css("color", "#000");
	$(".p5o").css("background-color", "#a9a9ae");
	$(".p5o").css("color", "#000");
	
	$(".p6r").css("background-color", "#a9a9ae");
	$(".p6r").css("color", "#000");
	$(".p7r").css("background-color", "#a9a9ae");
	$(".p7r").css("color", "#000");
	$(".p6e").css("background-color", "#a9a9ae");
	$(".p6e").css("color", "#000");
	$(".p7e").css("background-color", "#a9a9ae");
	$(".p7e").css("color", "#000");
	$(".p6o").css("background-color", "#a9a9ae");
	$(".p6o").css("color", "#000");
	$(".p7o").css("background-color", "#a9a9ae");
	$(".p7o").css("color", "#000");
	
	$(".p8r").css("background-color", "#a9a9ae");
	$(".p8r").css("color", "#000");
	$(".p9r").css("background-color", "#a9a9ae");
	$(".p9r").css("color", "#000");
	$(".p8e").css("background-color", "#a9a9ae");
	$(".p8e").css("color", "#000");
	$(".p9e").css("background-color", "#a9a9ae");
	$(".p9e").css("color", "#000");
	$(".p8o").css("background-color", "#a9a9ae");
	$(".p8o").css("color", "#000");
	$(".p9o").css("background-color", "#a9a9ae");
	$(".p9o").css("color", "#000");
	
	$(".p10r").css("background-color", "#a9a9ae");
	$(".p10r").css("color", "#000");
	$(".p11r").css("background-color", "#a9a9ae");
	$(".p11r").css("color", "#000");
	$(".p10e").css("background-color", "#a9a9ae");
	$(".p10e").css("color", "#000");
	$(".p11e").css("background-color", "#a9a9ae");
	$(".p11e").css("color", "#000");
	$(".p10o").css("background-color", "#a9a9ae");
	$(".p10o").css("color", "#000");
	$(".p11o").css("background-color", "#a9a9ae");
	$(".p11o").css("color", "#000");
	
	$(".p12r").css("background-color", "#a9a9ae");
	$(".p12r").css("color", "#000");
	$(".p13r").css("background-color", "#a9a9ae");
	$(".p13r").css("color", "#000");
	$(".p12e").css("background-color", "#a9a9ae");
	$(".p12e").css("color", "#000");
	$(".p13e").css("background-color", "#a9a9ae");
	$(".p13e").css("color", "#000");
	$(".p12o").css("background-color", "#a9a9ae");
	$(".p12o").css("color", "#000");
	$(".p13o").css("background-color", "#a9a9ae");
	$(".p13o").css("color", "#000");
	
	$(".p14r").css("background-color", "#a9a9ae");
	$(".p14r").css("color", "#000");
	$(".p15r").css("background-color", "#a9a9ae");
	$(".p15r").css("color", "#000");
	$(".p14e").css("background-color", "#a9a9ae");
	$(".p14e").css("color", "#000");
	$(".p15e").css("background-color", "#a9a9ae");
	$(".p15e").css("color", "#000");
	$(".p14o").css("background-color", "#a9a9ae");
	$(".p14o").css("color", "#000");
	$(".p15o").css("background-color", "#a9a9ae");
	$(".p15o").css("color", "#000");
	
	$(".p16r").css("background-color", "#a9a9ae");
	$(".p16r").css("color", "#000");
	$(".p17r").css("background-color", "#a9a9ae");
	$(".p17r").css("color", "#000");
	$(".p16e").css("background-color", "#a9a9ae");
	$(".p16e").css("color", "#000");
	$(".p17e").css("background-color", "#a9a9ae");
	$(".p17e").css("color", "#000");
	$(".p16o").css("background-color", "#a9a9ae");
	$(".p16o").css("color", "#000");
	$(".p17o").css("background-color", "#a9a9ae");
	$(".p17o").css("color", "#000");
	
	$(".p18r").css("background-color", "#a9a9ae");
	$(".p18r").css("color", "#000");
	$(".p19r").css("background-color", "#a9a9ae");
	$(".p19r").css("color", "#000");
	$(".p18e").css("background-color", "#a9a9ae");
	$(".p18e").css("color", "#000");
	$(".p19e").css("background-color", "#a9a9ae");
	$(".p19e").css("color", "#000");
	$(".p18o").css("background-color", "#a9a9ae");
	$(".p18o").css("color", "#000");
	$(".p19o").css("background-color", "#a9a9ae");
	$(".p19o").css("color", "#000");
	
	$(".p20r").css("background-color", "#a9a9ae");
	$(".p20r").css("color", "#000");
	$(".p21r").css("background-color", "#a9a9ae");
	$(".p21r").css("color", "#000");
	$(".p20e").css("background-color", "#a9a9ae");
	$(".p20e").css("color", "#000");
	$(".p21e").css("background-color", "#a9a9ae");
	$(".p21e").css("color", "#000");
	$(".p20o").css("background-color", "#a9a9ae");
	$(".p20o").css("color", "#000");
	$(".p21o").css("background-color", "#a9a9ae");
	$(".p21o").css("color", "#000");
	
	
  });
  
  $(".p4r,.p5r").click(function()
  {
	$("p.nEje3").css("background-color", "#5d2852");
	$(".p4r").css("background-color", "#5d2852");
	$(".p4r").css("color", "#fefefe");
	$(".p5r").css("background-color", "#5d2852");
	$(".p5r").css("color", "#fefefe");
	$(".p4e").css("background-color", "#5d2852");
	$(".p4e").css("color", "#fefefe");
	$(".p5e").css("background-color", "#5d2852");
	$(".p5e").css("color", "#fefefe");
	$(".p4o").css("background-color", "#5d2852");
	$(".p4o").css("color", "#fefefe");
	$(".p5o").css("background-color", "#5d2852");
	$(".p5o").css("color", "#fefefe");
	$(".franja").css("height", "223px");
	
	$("p.nEje1").css("background-color", "#4d4d57");
	$("p.nEje2").css("background-color", "#4d4d57");
	$("p.nEje4").css("background-color", "#4d4d57");
	$("p.nEje5").css("background-color", "#4d4d57");
	$("p.nEje6").css("background-color", "#4d4d57");
	$("p.nEje7").css("background-color", "#4d4d57");
	$("p.nEje8").css("background-color", "#4d4d57");
	$("p.nEje9").css("background-color", "#4d4d57");
	$("p.nEje10").css("background-color", "#4d4d57");
	$("p.nEje11").css("background-color", "#4d4d57");
	
	$(".p0r").css("background-color", "#a9a9ae");
	$(".p0r").css("color", "#000");
	$(".p1r").css("background-color", "#a9a9ae");
	$(".p1r").css("color", "#000");
	$(".p0e").css("background-color", "#a9a9ae");
	$(".p0e").css("color", "#000");
	$(".p1e").css("background-color", "#a9a9ae");
	$(".p1e").css("color", "#000");
	$(".p0o").css("background-color", "#a9a9ae");
	$(".p0o").css("color", "#000");
	$(".p1o").css("background-color", "#a9a9ae");
	$(".p1o").css("color", "#000");
	
	$(".p2r").css("background-color", "#a9a9ae");
	$(".p2r").css("color", "#000");
	$(".p3r").css("background-color", "#a9a9ae");
	$(".p3r").css("color", "#000");
	$(".p2e").css("background-color", "#a9a9ae");
	$(".p2e").css("color", "#000");
	$(".p3e").css("background-color", "#a9a9ae");
	$(".p3e").css("color", "#000");
	$(".p2o").css("background-color", "#a9a9ae");
	$(".p2o").css("color", "#000");
	$(".p3o").css("background-color", "#a9a9ae");
	$(".p3o").css("color", "#000");
	
	$(".p6r").css("background-color", "#a9a9ae");
	$(".p6r").css("color", "#000");
	$(".p7r").css("background-color", "#a9a9ae");
	$(".p7r").css("color", "#000");
	$(".p6e").css("background-color", "#a9a9ae");
	$(".p6e").css("color", "#000");
	$(".p7e").css("background-color", "#a9a9ae");
	$(".p7e").css("color", "#000");
	$(".p6o").css("background-color", "#a9a9ae");
	$(".p6o").css("color", "#000");
	$(".p7o").css("background-color", "#a9a9ae");
	$(".p7o").css("color", "#000");
	
	$(".p8r").css("background-color", "#a9a9ae");
	$(".p8r").css("color", "#000");
	$(".p9r").css("background-color", "#a9a9ae");
	$(".p9r").css("color", "#000");
	$(".p8e").css("background-color", "#a9a9ae");
	$(".p8e").css("color", "#000");
	$(".p9e").css("background-color", "#a9a9ae");
	$(".p9e").css("color", "#000");
	$(".p8o").css("background-color", "#a9a9ae");
	$(".p8o").css("color", "#000");
	$(".p9o").css("background-color", "#a9a9ae");
	$(".p9o").css("color", "#000");
	
	$(".p10r").css("background-color", "#a9a9ae");
	$(".p10r").css("color", "#000");
	$(".p11r").css("background-color", "#a9a9ae");
	$(".p11r").css("color", "#000");
	$(".p10e").css("background-color", "#a9a9ae");
	$(".p10e").css("color", "#000");
	$(".p11e").css("background-color", "#a9a9ae");
	$(".p11e").css("color", "#000");
	$(".p10o").css("background-color", "#a9a9ae");
	$(".p10o").css("color", "#000");
	$(".p11o").css("background-color", "#a9a9ae");
	$(".p11o").css("color", "#000");
	
	$(".p12r").css("background-color", "#a9a9ae");
	$(".p12r").css("color", "#000");
	$(".p13r").css("background-color", "#a9a9ae");
	$(".p13r").css("color", "#000");
	$(".p12e").css("background-color", "#a9a9ae");
	$(".p12e").css("color", "#000");
	$(".p13e").css("background-color", "#a9a9ae");
	$(".p13e").css("color", "#000");
	$(".p12o").css("background-color", "#a9a9ae");
	$(".p12o").css("color", "#000");
	$(".p13o").css("background-color", "#a9a9ae");
	$(".p13o").css("color", "#000");
	
	$(".p14r").css("background-color", "#a9a9ae");
	$(".p14r").css("color", "#000");
	$(".p15r").css("background-color", "#a9a9ae");
	$(".p15r").css("color", "#000");
	$(".p14e").css("background-color", "#a9a9ae");
	$(".p14e").css("color", "#000");
	$(".p15e").css("background-color", "#a9a9ae");
	$(".p15e").css("color", "#000");
	$(".p14o").css("background-color", "#a9a9ae");
	$(".p14o").css("color", "#000");
	$(".p15o").css("background-color", "#a9a9ae");
	$(".p15o").css("color", "#000");
	
	$(".p16r").css("background-color", "#a9a9ae");
	$(".p16r").css("color", "#000");
	$(".p17r").css("background-color", "#a9a9ae");
	$(".p17r").css("color", "#000");
	$(".p16e").css("background-color", "#a9a9ae");
	$(".p16e").css("color", "#000");
	$(".p17e").css("background-color", "#a9a9ae");
	$(".p17e").css("color", "#000");
	$(".p16o").css("background-color", "#a9a9ae");
	$(".p16o").css("color", "#000");
	$(".p17o").css("background-color", "#a9a9ae");
	$(".p17o").css("color", "#000");
	
	$(".p18r").css("background-color", "#a9a9ae");
	$(".p18r").css("color", "#000");
	$(".p19r").css("background-color", "#a9a9ae");
	$(".p19r").css("color", "#000");
	$(".p18e").css("background-color", "#a9a9ae");
	$(".p18e").css("color", "#000");
	$(".p19e").css("background-color", "#a9a9ae");
	$(".p19e").css("color", "#000");
	$(".p18o").css("background-color", "#a9a9ae");
	$(".p18o").css("color", "#000");
	$(".p19o").css("background-color", "#a9a9ae");
	$(".p19o").css("color", "#000");
	
	$(".p20r").css("background-color", "#a9a9ae");
	$(".p20r").css("color", "#000");
	$(".p21r").css("background-color", "#a9a9ae");
	$(".p21r").css("color", "#000");
	$(".p20e").css("background-color", "#a9a9ae");
	$(".p20e").css("color", "#000");
	$(".p21e").css("background-color", "#a9a9ae");
	$(".p21e").css("color", "#000");
	$(".p20o").css("background-color", "#a9a9ae");
	$(".p20o").css("color", "#000");
	$(".p21o").css("background-color", "#a9a9ae");
	$(".p21o").css("color", "#000");
  });
  
  $(".p6r,.p7r").click(function()
  {
	$("p.nEje4").css("background-color", "#5d2852");
	$(".p6r").css("background-color", "#5d2852");
	$(".p6r").css("color", "#fefefe");
	$(".p7r").css("background-color", "#5d2852");
	$(".p7r").css("color", "#fefefe");
	$(".p6e").css("background-color", "#5d2852");
	$(".p6e").css("color", "#fefefe");
	$(".p7e").css("background-color", "#5d2852");
	$(".p7e").css("color", "#fefefe");
	$(".p6o").css("background-color", "#5d2852");
	$(".p6o").css("color", "#fefefe");
	$(".p7o").css("background-color", "#5d2852");
	$(".p7o").css("color", "#fefefe");
	$(".franja").css("height", "275px");
	
	$("p.nEje1").css("background-color", "#4d4d57");
	$("p.nEje2").css("background-color", "#4d4d57");
	$("p.nEje3").css("background-color", "#4d4d57");
	$("p.nEje5").css("background-color", "#4d4d57");
	$("p.nEje6").css("background-color", "#4d4d57");
	$("p.nEje7").css("background-color", "#4d4d57");
	$("p.nEje8").css("background-color", "#4d4d57");
	$("p.nEje9").css("background-color", "#4d4d57");
	$("p.nEje10").css("background-color", "#4d4d57");
	$("p.nEje11").css("background-color", "#4d4d57");
	
	$(".p0r").css("background-color", "#a9a9ae");
	$(".p0r").css("color", "#000");
	$(".p1r").css("background-color", "#a9a9ae");
	$(".p1r").css("color", "#000");
	$(".p0e").css("background-color", "#a9a9ae");
	$(".p0e").css("color", "#000");
	$(".p1e").css("background-color", "#a9a9ae");
	$(".p1e").css("color", "#000");
	$(".p0o").css("background-color", "#a9a9ae");
	$(".p0o").css("color", "#000");
	$(".p1o").css("background-color", "#a9a9ae");
	$(".p1o").css("color", "#000");
	
	$(".p2r").css("background-color", "#a9a9ae");
	$(".p2r").css("color", "#000");
	$(".p3r").css("background-color", "#a9a9ae");
	$(".p3r").css("color", "#000");
	$(".p2e").css("background-color", "#a9a9ae");
	$(".p2e").css("color", "#000");
	$(".p3e").css("background-color", "#a9a9ae");
	$(".p3e").css("color", "#000");
	$(".p2o").css("background-color", "#a9a9ae");
	$(".p2o").css("color", "#000");
	$(".p3o").css("background-color", "#a9a9ae");
	$(".p3o").css("color", "#000");
	
	$(".p4r").css("background-color", "#a9a9ae");
	$(".p4r").css("color", "#000");
	$(".p5r").css("background-color", "#a9a9ae");
	$(".p5r").css("color", "#000");
	$(".p4e").css("background-color", "#a9a9ae");
	$(".p4e").css("color", "#000");
	$(".p5e").css("background-color", "#a9a9ae");
	$(".p5e").css("color", "#000");
	$(".p4o").css("background-color", "#a9a9ae");
	$(".p4o").css("color", "#000");
	$(".p5o").css("background-color", "#a9a9ae");
	$(".p5o").css("color", "#000");
	
	$(".p8r").css("background-color", "#a9a9ae");
	$(".p8r").css("color", "#000");
	$(".p9r").css("background-color", "#a9a9ae");
	$(".p9r").css("color", "#000");
	$(".p8e").css("background-color", "#a9a9ae");
	$(".p8e").css("color", "#000");
	$(".p9e").css("background-color", "#a9a9ae");
	$(".p9e").css("color", "#000");
	$(".p8o").css("background-color", "#a9a9ae");
	$(".p8o").css("color", "#000");
	$(".p9o").css("background-color", "#a9a9ae");
	$(".p9o").css("color", "#000");
	
	$(".p10r").css("background-color", "#a9a9ae");
	$(".p10r").css("color", "#000");
	$(".p11r").css("background-color", "#a9a9ae");
	$(".p11r").css("color", "#000");
	$(".p10e").css("background-color", "#a9a9ae");
	$(".p10e").css("color", "#000");
	$(".p11e").css("background-color", "#a9a9ae");
	$(".p11e").css("color", "#000");
	$(".p10o").css("background-color", "#a9a9ae");
	$(".p10o").css("color", "#000");
	$(".p11o").css("background-color", "#a9a9ae");
	$(".p11o").css("color", "#000");
	
	$(".p12r").css("background-color", "#a9a9ae");
	$(".p12r").css("color", "#000");
	$(".p13r").css("background-color", "#a9a9ae");
	$(".p13r").css("color", "#000");
	$(".p12e").css("background-color", "#a9a9ae");
	$(".p12e").css("color", "#000");
	$(".p13e").css("background-color", "#a9a9ae");
	$(".p13e").css("color", "#000");
	$(".p12o").css("background-color", "#a9a9ae");
	$(".p12o").css("color", "#000");
	$(".p13o").css("background-color", "#a9a9ae");
	$(".p13o").css("color", "#000");
	
	$(".p14r").css("background-color", "#a9a9ae");
	$(".p14r").css("color", "#000");
	$(".p15r").css("background-color", "#a9a9ae");
	$(".p15r").css("color", "#000");
	$(".p14e").css("background-color", "#a9a9ae");
	$(".p14e").css("color", "#000");
	$(".p15e").css("background-color", "#a9a9ae");
	$(".p15e").css("color", "#000");
	$(".p14o").css("background-color", "#a9a9ae");
	$(".p14o").css("color", "#000");
	$(".p15o").css("background-color", "#a9a9ae");
	$(".p15o").css("color", "#000");
	
	$(".p16r").css("background-color", "#a9a9ae");
	$(".p16r").css("color", "#000");
	$(".p17r").css("background-color", "#a9a9ae");
	$(".p17r").css("color", "#000");
	$(".p16e").css("background-color", "#a9a9ae");
	$(".p16e").css("color", "#000");
	$(".p17e").css("background-color", "#a9a9ae");
	$(".p17e").css("color", "#000");
	$(".p16o").css("background-color", "#a9a9ae");
	$(".p16o").css("color", "#000");
	$(".p17o").css("background-color", "#a9a9ae");
	$(".p17o").css("color", "#000");
	
	$(".p18r").css("background-color", "#a9a9ae");
	$(".p18r").css("color", "#000");
	$(".p19r").css("background-color", "#a9a9ae");
	$(".p19r").css("color", "#000");
	$(".p18e").css("background-color", "#a9a9ae");
	$(".p18e").css("color", "#000");
	$(".p19e").css("background-color", "#a9a9ae");
	$(".p19e").css("color", "#000");
	$(".p18o").css("background-color", "#a9a9ae");
	$(".p18o").css("color", "#000");
	$(".p19o").css("background-color", "#a9a9ae");
	$(".p19o").css("color", "#000");
	
	$(".p20r").css("background-color", "#a9a9ae");
	$(".p20r").css("color", "#000");
	$(".p21r").css("background-color", "#a9a9ae");
	$(".p21r").css("color", "#000");
	$(".p20e").css("background-color", "#a9a9ae");
	$(".p20e").css("color", "#000");
	$(".p21e").css("background-color", "#a9a9ae");
	$(".p21e").css("color", "#000");
	$(".p20o").css("background-color", "#a9a9ae");
	$(".p20o").css("color", "#000");
	$(".p21o").css("background-color", "#a9a9ae");
	$(".p21o").css("color", "#000");
  });
  
  $(".p8r,.p9r").click(function()
  {
	$("p.nEje5").css("background-color", "#5d2852");
	$(".p8r").css("background-color", "#5d2852");
	$(".p8r").css("color", "#fefefe");
	$(".p9r").css("background-color", "#5d2852");
	$(".p9r").css("color", "#fefefe");
	$(".p8e").css("background-color", "#5d2852");
	$(".p8e").css("color", "#fefefe");
	$(".p9e").css("background-color", "#5d2852");
	$(".p9e").css("color", "#fefefe");
	$(".p8o").css("background-color", "#5d2852");
	$(".p8o").css("color", "#fefefe");
	$(".p9o").css("background-color", "#5d2852");
	$(".p9o").css("color", "#fefefe");
	$(".franja").css("height", "329px");
	
	$("p.nEje1").css("background-color", "#4d4d57");
	$("p.nEje2").css("background-color", "#4d4d57");
	$("p.nEje3").css("background-color", "#4d4d57");
	$("p.nEje4").css("background-color", "#4d4d57");
	$("p.nEje6").css("background-color", "#4d4d57");
	$("p.nEje7").css("background-color", "#4d4d57");
	$("p.nEje8").css("background-color", "#4d4d57");
	$("p.nEje9").css("background-color", "#4d4d57");
	$("p.nEje10").css("background-color", "#4d4d57");
	$("p.nEje11").css("background-color", "#4d4d57");
	
	$(".p0r").css("background-color", "#a9a9ae");
	$(".p0r").css("color", "#000");
	$(".p1r").css("background-color", "#a9a9ae");
	$(".p1r").css("color", "#000");
	$(".p0e").css("background-color", "#a9a9ae");
	$(".p0e").css("color", "#000");
	$(".p1e").css("background-color", "#a9a9ae");
	$(".p1e").css("color", "#000");
	$(".p0o").css("background-color", "#a9a9ae");
	$(".p0o").css("color", "#000");
	$(".p1o").css("background-color", "#a9a9ae");
	$(".p1o").css("color", "#000");
	
	$(".p2r").css("background-color", "#a9a9ae");
	$(".p2r").css("color", "#000");
	$(".p3r").css("background-color", "#a9a9ae");
	$(".p3r").css("color", "#000");
	$(".p2e").css("background-color", "#a9a9ae");
	$(".p2e").css("color", "#000");
	$(".p3e").css("background-color", "#a9a9ae");
	$(".p3e").css("color", "#000");
	$(".p2o").css("background-color", "#a9a9ae");
	$(".p2o").css("color", "#000");
	$(".p3o").css("background-color", "#a9a9ae");
	$(".p3o").css("color", "#000");
	
	$(".p4r").css("background-color", "#a9a9ae");
	$(".p4r").css("color", "#000");
	$(".p5r").css("background-color", "#a9a9ae");
	$(".p5r").css("color", "#000");
	$(".p4e").css("background-color", "#a9a9ae");
	$(".p4e").css("color", "#000");
	$(".p5e").css("background-color", "#a9a9ae");
	$(".p5e").css("color", "#000");
	$(".p4o").css("background-color", "#a9a9ae");
	$(".p4o").css("color", "#000");
	$(".p5o").css("background-color", "#a9a9ae");
	$(".p5o").css("color", "#000");
	
	$(".p6r").css("background-color", "#a9a9ae");
	$(".p6r").css("color", "#000");
	$(".p7r").css("background-color", "#a9a9ae");
	$(".p7r").css("color", "#000");
	$(".p6e").css("background-color", "#a9a9ae");
	$(".p6e").css("color", "#000");
	$(".p7e").css("background-color", "#a9a9ae");
	$(".p7e").css("color", "#000");
	$(".p6o").css("background-color", "#a9a9ae");
	$(".p6o").css("color", "#000");
	$(".p7o").css("background-color", "#a9a9ae");
	$(".p7o").css("color", "#000");
	
	$(".p10r").css("background-color", "#a9a9ae");
	$(".p10r").css("color", "#000");
	$(".p11r").css("background-color", "#a9a9ae");
	$(".p11r").css("color", "#000");
	$(".p10e").css("background-color", "#a9a9ae");
	$(".p10e").css("color", "#000");
	$(".p11e").css("background-color", "#a9a9ae");
	$(".p11e").css("color", "#000");
	$(".p10o").css("background-color", "#a9a9ae");
	$(".p10o").css("color", "#000");
	$(".p11o").css("background-color", "#a9a9ae");
	$(".p11o").css("color", "#000");
	
	$(".p12r").css("background-color", "#a9a9ae");
	$(".p12r").css("color", "#000");
	$(".p13r").css("background-color", "#a9a9ae");
	$(".p13r").css("color", "#000");
	$(".p12e").css("background-color", "#a9a9ae");
	$(".p12e").css("color", "#000");
	$(".p13e").css("background-color", "#a9a9ae");
	$(".p13e").css("color", "#000");
	$(".p12o").css("background-color", "#a9a9ae");
	$(".p12o").css("color", "#000");
	$(".p13o").css("background-color", "#a9a9ae");
	$(".p13o").css("color", "#000");
	
	$(".p14r").css("background-color", "#a9a9ae");
	$(".p14r").css("color", "#000");
	$(".p15r").css("background-color", "#a9a9ae");
	$(".p15r").css("color", "#000");
	$(".p14e").css("background-color", "#a9a9ae");
	$(".p14e").css("color", "#000");
	$(".p15e").css("background-color", "#a9a9ae");
	$(".p15e").css("color", "#000");
	$(".p14o").css("background-color", "#a9a9ae");
	$(".p14o").css("color", "#000");
	$(".p15o").css("background-color", "#a9a9ae");
	$(".p15o").css("color", "#000");
	
	$(".p16r").css("background-color", "#a9a9ae");
	$(".p16r").css("color", "#000");
	$(".p17r").css("background-color", "#a9a9ae");
	$(".p17r").css("color", "#000");
	$(".p16e").css("background-color", "#a9a9ae");
	$(".p16e").css("color", "#000");
	$(".p17e").css("background-color", "#a9a9ae");
	$(".p17e").css("color", "#000");
	$(".p16o").css("background-color", "#a9a9ae");
	$(".p16o").css("color", "#000");
	$(".p17o").css("background-color", "#a9a9ae");
	$(".p17o").css("color", "#000");
	
	$(".p18r").css("background-color", "#a9a9ae");
	$(".p18r").css("color", "#000");
	$(".p19r").css("background-color", "#a9a9ae");
	$(".p19r").css("color", "#000");
	$(".p18e").css("background-color", "#a9a9ae");
	$(".p18e").css("color", "#000");
	$(".p19e").css("background-color", "#a9a9ae");
	$(".p19e").css("color", "#000");
	$(".p18o").css("background-color", "#a9a9ae");
	$(".p18o").css("color", "#000");
	$(".p19o").css("background-color", "#a9a9ae");
	$(".p19o").css("color", "#000");
	
	$(".p20r").css("background-color", "#a9a9ae");
	$(".p20r").css("color", "#000");
	$(".p21r").css("background-color", "#a9a9ae");
	$(".p21r").css("color", "#000");
	$(".p20e").css("background-color", "#a9a9ae");
	$(".p20e").css("color", "#000");
	$(".p21e").css("background-color", "#a9a9ae");
	$(".p21e").css("color", "#000");
	$(".p20o").css("background-color", "#a9a9ae");
	$(".p20o").css("color", "#000");
	$(".p21o").css("background-color", "#a9a9ae");
	$(".p21o").css("color", "#000");
  });
  
    $(".p10r,.p11r").click(function()
  {
	$("p.nEje6").css("background-color", "#5d2852");
	$(".p10r").css("background-color", "#5d2852");
	$(".p10r").css("color", "#fefefe");
	$(".p11r").css("background-color", "#5d2852");
	$(".p11r").css("color", "#fefefe");
	$(".p10e").css("background-color", "#5d2852");
	$(".p10e").css("color", "#fefefe");
	$(".p11e").css("background-color", "#5d2852");
	$(".p11e").css("color", "#fefefe");
	$(".p10o").css("background-color", "#5d2852");
	$(".p10o").css("color", "#fefefe");
	$(".p11o").css("background-color", "#5d2852");
	$(".p11o").css("color", "#fefefe");
	$(".franja").css("height", "382px");
	
	$("p.nEje1").css("background-color", "#4d4d57");
	$("p.nEje2").css("background-color", "#4d4d57");
	$("p.nEje3").css("background-color", "#4d4d57");
	$("p.nEje4").css("background-color", "#4d4d57");
	$("p.nEje5").css("background-color", "#4d4d57");
	$("p.nEje7").css("background-color", "#4d4d57");
	$("p.nEje8").css("background-color", "#4d4d57");
	$("p.nEje9").css("background-color", "#4d4d57");
	$("p.nEje10").css("background-color", "#4d4d57");
	$("p.nEje11").css("background-color", "#4d4d57");
	
	$(".p0r").css("background-color", "#a9a9ae");
	$(".p0r").css("color", "#000");
	$(".p1r").css("background-color", "#a9a9ae");
	$(".p1r").css("color", "#000");
	$(".p0e").css("background-color", "#a9a9ae");
	$(".p0e").css("color", "#000");
	$(".p1e").css("background-color", "#a9a9ae");
	$(".p1e").css("color", "#000");
	$(".p0o").css("background-color", "#a9a9ae");
	$(".p0o").css("color", "#000");
	$(".p1o").css("background-color", "#a9a9ae");
	$(".p1o").css("color", "#000");
	
	$(".p2r").css("background-color", "#a9a9ae");
	$(".p2r").css("color", "#000");
	$(".p3r").css("background-color", "#a9a9ae");
	$(".p3r").css("color", "#000");
	$(".p2e").css("background-color", "#a9a9ae");
	$(".p2e").css("color", "#000");
	$(".p3e").css("background-color", "#a9a9ae");
	$(".p3e").css("color", "#000");
	$(".p2o").css("background-color", "#a9a9ae");
	$(".p2o").css("color", "#000");
	$(".p3o").css("background-color", "#a9a9ae");
	$(".p3o").css("color", "#000");
	
	$(".p4r").css("background-color", "#a9a9ae");
	$(".p4r").css("color", "#000");
	$(".p5r").css("background-color", "#a9a9ae");
	$(".p5r").css("color", "#000");
	$(".p4e").css("background-color", "#a9a9ae");
	$(".p4e").css("color", "#000");
	$(".p5e").css("background-color", "#a9a9ae");
	$(".p5e").css("color", "#000");
	$(".p4o").css("background-color", "#a9a9ae");
	$(".p4o").css("color", "#000");
	$(".p5o").css("background-color", "#a9a9ae");
	$(".p5o").css("color", "#000");
	
	$(".p6r").css("background-color", "#a9a9ae");
	$(".p6r").css("color", "#000");
	$(".p7r").css("background-color", "#a9a9ae");
	$(".p7r").css("color", "#000");
	$(".p6e").css("background-color", "#a9a9ae");
	$(".p6e").css("color", "#000");
	$(".p7e").css("background-color", "#a9a9ae");
	$(".p7e").css("color", "#000");
	$(".p6o").css("background-color", "#a9a9ae");
	$(".p6o").css("color", "#000");
	$(".p7o").css("background-color", "#a9a9ae");
	$(".p7o").css("color", "#000");
	
	$(".p8r").css("background-color", "#a9a9ae");
	$(".p8r").css("color", "#000");
	$(".p9r").css("background-color", "#a9a9ae");
	$(".p9r").css("color", "#000");
	$(".p8e").css("background-color", "#a9a9ae");
	$(".p8e").css("color", "#000");
	$(".p9e").css("background-color", "#a9a9ae");
	$(".p9e").css("color", "#000");
	$(".p8o").css("background-color", "#a9a9ae");
	$(".p8o").css("color", "#000");
	$(".p9o").css("background-color", "#a9a9ae");
	$(".p9o").css("color", "#000");
	
	$(".p12r").css("background-color", "#a9a9ae");
	$(".p12r").css("color", "#000");
	$(".p13r").css("background-color", "#a9a9ae");
	$(".p13r").css("color", "#000");
	$(".p12e").css("background-color", "#a9a9ae");
	$(".p12e").css("color", "#000");
	$(".p13e").css("background-color", "#a9a9ae");
	$(".p13e").css("color", "#000");
	$(".p12o").css("background-color", "#a9a9ae");
	$(".p12o").css("color", "#000");
	$(".p13o").css("background-color", "#a9a9ae");
	$(".p13o").css("color", "#000");
	
	$(".p14r").css("background-color", "#a9a9ae");
	$(".p14r").css("color", "#000");
	$(".p15r").css("background-color", "#a9a9ae");
	$(".p15r").css("color", "#000");
	$(".p14e").css("background-color", "#a9a9ae");
	$(".p14e").css("color", "#000");
	$(".p15e").css("background-color", "#a9a9ae");
	$(".p15e").css("color", "#000");
	$(".p14o").css("background-color", "#a9a9ae");
	$(".p14o").css("color", "#000");
	$(".p15o").css("background-color", "#a9a9ae");
	$(".p15o").css("color", "#000");
	
	$(".p16r").css("background-color", "#a9a9ae");
	$(".p16r").css("color", "#000");
	$(".p17r").css("background-color", "#a9a9ae");
	$(".p17r").css("color", "#000");
	$(".p16e").css("background-color", "#a9a9ae");
	$(".p16e").css("color", "#000");
	$(".p17e").css("background-color", "#a9a9ae");
	$(".p17e").css("color", "#000");
	$(".p16o").css("background-color", "#a9a9ae");
	$(".p16o").css("color", "#000");
	$(".p17o").css("background-color", "#a9a9ae");
	$(".p17o").css("color", "#000");
	
	$(".p18r").css("background-color", "#a9a9ae");
	$(".p18r").css("color", "#000");
	$(".p19r").css("background-color", "#a9a9ae");
	$(".p19r").css("color", "#000");
	$(".p18e").css("background-color", "#a9a9ae");
	$(".p18e").css("color", "#000");
	$(".p19e").css("background-color", "#a9a9ae");
	$(".p19e").css("color", "#000");
	$(".p18o").css("background-color", "#a9a9ae");
	$(".p18o").css("color", "#000");
	$(".p19o").css("background-color", "#a9a9ae");
	$(".p19o").css("color", "#000");
	
	$(".p20r").css("background-color", "#a9a9ae");
	$(".p20r").css("color", "#000");
	$(".p21r").css("background-color", "#a9a9ae");
	$(".p21r").css("color", "#000");
	$(".p20e").css("background-color", "#a9a9ae");
	$(".p20e").css("color", "#000");
	$(".p21e").css("background-color", "#a9a9ae");
	$(".p21e").css("color", "#000");
	$(".p20o").css("background-color", "#a9a9ae");
	$(".p20o").css("color", "#000");
	$(".p21o").css("background-color", "#a9a9ae");
	$(".p21o").css("color", "#000");
  });
  
  $(".p12r,.p13r").click(function()
  {
	$("p.nEje7").css("background-color", "#5d2852");
	$(".p12r").css("background-color", "#5d2852");
	$(".p12r").css("color", "#fefefe");
	$(".p13r").css("background-color", "#5d2852");
	$(".p13r").css("color", "#fefefe");
	$(".p12e").css("background-color", "#5d2852");
	$(".p12e").css("color", "#fefefe");
	$(".p13e").css("background-color", "#5d2852");
	$(".p13e").css("color", "#fefefe");
	$(".p12o").css("background-color", "#5d2852");
	$(".p12o").css("color", "#fefefe");
	$(".p13o").css("background-color", "#5d2852");
	$(".p13o").css("color", "#fefefe");
	$(".franja").css("height", "435px");
	
	$("p.nEje1").css("background-color", "#4d4d57");
	$("p.nEje2").css("background-color", "#4d4d57");
	$("p.nEje3").css("background-color", "#4d4d57");
	$("p.nEje4").css("background-color", "#4d4d57");
	$("p.nEje5").css("background-color", "#4d4d57");
	$("p.nEje6").css("background-color", "#4d4d57");
	$("p.nEje8").css("background-color", "#4d4d57");
	$("p.nEje9").css("background-color", "#4d4d57");
	$("p.nEje10").css("background-color", "#4d4d57");
	$("p.nEje11").css("background-color", "#4d4d57");
	
	$(".p0r").css("background-color", "#a9a9ae");
	$(".p0r").css("color", "#000");
	$(".p1r").css("background-color", "#a9a9ae");
	$(".p1r").css("color", "#000");
	$(".p0e").css("background-color", "#a9a9ae");
	$(".p0e").css("color", "#000");
	$(".p1e").css("background-color", "#a9a9ae");
	$(".p1e").css("color", "#000");
	$(".p0o").css("background-color", "#a9a9ae");
	$(".p0o").css("color", "#000");
	$(".p1o").css("background-color", "#a9a9ae");
	$(".p1o").css("color", "#000");
	
	$(".p2r").css("background-color", "#a9a9ae");
	$(".p2r").css("color", "#000");
	$(".p3r").css("background-color", "#a9a9ae");
	$(".p3r").css("color", "#000");
	$(".p2e").css("background-color", "#a9a9ae");
	$(".p2e").css("color", "#000");
	$(".p3e").css("background-color", "#a9a9ae");
	$(".p3e").css("color", "#000");
	$(".p2o").css("background-color", "#a9a9ae");
	$(".p2o").css("color", "#000");
	$(".p3o").css("background-color", "#a9a9ae");
	$(".p3o").css("color", "#000");
	
	$(".p4r").css("background-color", "#a9a9ae");
	$(".p4r").css("color", "#000");
	$(".p5r").css("background-color", "#a9a9ae");
	$(".p5r").css("color", "#000");
	$(".p4e").css("background-color", "#a9a9ae");
	$(".p4e").css("color", "#000");
	$(".p5e").css("background-color", "#a9a9ae");
	$(".p5e").css("color", "#000");
	$(".p4o").css("background-color", "#a9a9ae");
	$(".p4o").css("color", "#000");
	$(".p5o").css("background-color", "#a9a9ae");
	$(".p5o").css("color", "#000");
	
	$(".p6r").css("background-color", "#a9a9ae");
	$(".p6r").css("color", "#000");
	$(".p7r").css("background-color", "#a9a9ae");
	$(".p7r").css("color", "#000");
	$(".p6e").css("background-color", "#a9a9ae");
	$(".p6e").css("color", "#000");
	$(".p7e").css("background-color", "#a9a9ae");
	$(".p7e").css("color", "#000");
	$(".p6o").css("background-color", "#a9a9ae");
	$(".p6o").css("color", "#000");
	$(".p7o").css("background-color", "#a9a9ae");
	$(".p7o").css("color", "#000");
	
	$(".p8r").css("background-color", "#a9a9ae");
	$(".p8r").css("color", "#000");
	$(".p9r").css("background-color", "#a9a9ae");
	$(".p9r").css("color", "#000");
	$(".p8e").css("background-color", "#a9a9ae");
	$(".p8e").css("color", "#000");
	$(".p9e").css("background-color", "#a9a9ae");
	$(".p9e").css("color", "#000");
	$(".p8o").css("background-color", "#a9a9ae");
	$(".p8o").css("color", "#000");
	$(".p9o").css("background-color", "#a9a9ae");
	$(".p9o").css("color", "#000");
	
	$(".p10r").css("background-color", "#a9a9ae");
	$(".p10r").css("color", "#000");
	$(".p11r").css("background-color", "#a9a9ae");
	$(".p11r").css("color", "#000");
	$(".p10e").css("background-color", "#a9a9ae");
	$(".p10e").css("color", "#000");
	$(".p11e").css("background-color", "#a9a9ae");
	$(".p11e").css("color", "#000");
	$(".p10o").css("background-color", "#a9a9ae");
	$(".p10o").css("color", "#000");
	$(".p11o").css("background-color", "#a9a9ae");
	$(".p11o").css("color", "#000");
	
	$(".p14r").css("background-color", "#a9a9ae");
	$(".p14r").css("color", "#000");
	$(".p15r").css("background-color", "#a9a9ae");
	$(".p15r").css("color", "#000");
	$(".p14e").css("background-color", "#a9a9ae");
	$(".p14e").css("color", "#000");
	$(".p15e").css("background-color", "#a9a9ae");
	$(".p15e").css("color", "#000");
	$(".p14o").css("background-color", "#a9a9ae");
	$(".p14o").css("color", "#000");
	$(".p15o").css("background-color", "#a9a9ae");
	$(".p15o").css("color", "#000");
	
	$(".p16r").css("background-color", "#a9a9ae");
	$(".p16r").css("color", "#000");
	$(".p17r").css("background-color", "#a9a9ae");
	$(".p17r").css("color", "#000");
	$(".p16e").css("background-color", "#a9a9ae");
	$(".p16e").css("color", "#000");
	$(".p17e").css("background-color", "#a9a9ae");
	$(".p17e").css("color", "#000");
	$(".p16o").css("background-color", "#a9a9ae");
	$(".p16o").css("color", "#000");
	$(".p17o").css("background-color", "#a9a9ae");
	$(".p17o").css("color", "#000");
	
	$(".p18r").css("background-color", "#a9a9ae");
	$(".p18r").css("color", "#000");
	$(".p19r").css("background-color", "#a9a9ae");
	$(".p19r").css("color", "#000");
	$(".p18e").css("background-color", "#a9a9ae");
	$(".p18e").css("color", "#000");
	$(".p19e").css("background-color", "#a9a9ae");
	$(".p19e").css("color", "#000");
	$(".p18o").css("background-color", "#a9a9ae");
	$(".p18o").css("color", "#000");
	$(".p19o").css("background-color", "#a9a9ae");
	$(".p19o").css("color", "#000");
	
	$(".p20r").css("background-color", "#a9a9ae");
	$(".p20r").css("color", "#000");
	$(".p21r").css("background-color", "#a9a9ae");
	$(".p21r").css("color", "#000");
	$(".p20e").css("background-color", "#a9a9ae");
	$(".p20e").css("color", "#000");
	$(".p21e").css("background-color", "#a9a9ae");
	$(".p21e").css("color", "#000");
	$(".p20o").css("background-color", "#a9a9ae");
	$(".p20o").css("color", "#000");
	$(".p21o").css("background-color", "#a9a9ae");
	$(".p21o").css("color", "#000");
  });
  
  $(".p14r,.p15r").click(function()
  {
	$("p.nEje8").css("background-color", "#5d2852");
	$(".p14r").css("background-color", "#5d2852");
	$(".p14r").css("color", "#fefefe");
	$(".p15r").css("background-color", "#5d2852");
	$(".p15r").css("color", "#fefefe");
	$(".p14e").css("background-color", "#5d2852");
	$(".p14e").css("color", "#fefefe");
	$(".p15e").css("background-color", "#5d2852");
	$(".p15e").css("color", "#fefefe");
	$(".p14o").css("background-color", "#5d2852");
	$(".p14o").css("color", "#fefefe");
	$(".p15o").css("background-color", "#5d2852");
	$(".p15o").css("color", "#fefefe");
	$(".franja").css("height", "488px");
	
	$("p.nEje1").css("background-color", "#4d4d57");
	$("p.nEje2").css("background-color", "#4d4d57");
	$("p.nEje3").css("background-color", "#4d4d57");
	$("p.nEje4").css("background-color", "#4d4d57");
	$("p.nEje5").css("background-color", "#4d4d57");
	$("p.nEje6").css("background-color", "#4d4d57");
	$("p.nEje7").css("background-color", "#4d4d57");
	$("p.nEje9").css("background-color", "#4d4d57");
	$("p.nEje10").css("background-color", "#4d4d57");
	$("p.nEje11").css("background-color", "#4d4d57");
	
	$(".p0r").css("background-color", "#a9a9ae");
	$(".p0r").css("color", "#000");
	$(".p1r").css("background-color", "#a9a9ae");
	$(".p1r").css("color", "#000");
	$(".p0e").css("background-color", "#a9a9ae");
	$(".p0e").css("color", "#000");
	$(".p1e").css("background-color", "#a9a9ae");
	$(".p1e").css("color", "#000");
	$(".p0o").css("background-color", "#a9a9ae");
	$(".p0o").css("color", "#000");
	$(".p1o").css("background-color", "#a9a9ae");
	$(".p1o").css("color", "#000");
	
	$(".p2r").css("background-color", "#a9a9ae");
	$(".p2r").css("color", "#000");
	$(".p3r").css("background-color", "#a9a9ae");
	$(".p3r").css("color", "#000");
	$(".p2e").css("background-color", "#a9a9ae");
	$(".p2e").css("color", "#000");
	$(".p3e").css("background-color", "#a9a9ae");
	$(".p3e").css("color", "#000");
	$(".p2o").css("background-color", "#a9a9ae");
	$(".p2o").css("color", "#000");
	$(".p3o").css("background-color", "#a9a9ae");
	$(".p3o").css("color", "#000");
	
	$(".p4r").css("background-color", "#a9a9ae");
	$(".p4r").css("color", "#000");
	$(".p5r").css("background-color", "#a9a9ae");
	$(".p5r").css("color", "#000");
	$(".p4e").css("background-color", "#a9a9ae");
	$(".p4e").css("color", "#000");
	$(".p5e").css("background-color", "#a9a9ae");
	$(".p5e").css("color", "#000");
	$(".p4o").css("background-color", "#a9a9ae");
	$(".p4o").css("color", "#000");
	$(".p5o").css("background-color", "#a9a9ae");
	$(".p5o").css("color", "#000");
	
	$(".p6r").css("background-color", "#a9a9ae");
	$(".p6r").css("color", "#000");
	$(".p7r").css("background-color", "#a9a9ae");
	$(".p7r").css("color", "#000");
	$(".p6e").css("background-color", "#a9a9ae");
	$(".p6e").css("color", "#000");
	$(".p7e").css("background-color", "#a9a9ae");
	$(".p7e").css("color", "#000");
	$(".p6o").css("background-color", "#a9a9ae");
	$(".p6o").css("color", "#000");
	$(".p7o").css("background-color", "#a9a9ae");
	$(".p7o").css("color", "#000");
	
	$(".p8r").css("background-color", "#a9a9ae");
	$(".p8r").css("color", "#000");
	$(".p9r").css("background-color", "#a9a9ae");
	$(".p9r").css("color", "#000");
	$(".p8e").css("background-color", "#a9a9ae");
	$(".p8e").css("color", "#000");
	$(".p9e").css("background-color", "#a9a9ae");
	$(".p9e").css("color", "#000");
	$(".p8o").css("background-color", "#a9a9ae");
	$(".p8o").css("color", "#000");
	$(".p9o").css("background-color", "#a9a9ae");
	$(".p9o").css("color", "#000");
	
	$(".p10r").css("background-color", "#a9a9ae");
	$(".p10r").css("color", "#000");
	$(".p11r").css("background-color", "#a9a9ae");
	$(".p11r").css("color", "#000");
	$(".p10e").css("background-color", "#a9a9ae");
	$(".p10e").css("color", "#000");
	$(".p11e").css("background-color", "#a9a9ae");
	$(".p11e").css("color", "#000");
	$(".p10o").css("background-color", "#a9a9ae");
	$(".p10o").css("color", "#000");
	$(".p11o").css("background-color", "#a9a9ae");
	$(".p11o").css("color", "#000");
	
	$(".p12r").css("background-color", "#a9a9ae");
	$(".p12r").css("color", "#000");
	$(".p13r").css("background-color", "#a9a9ae");
	$(".p13r").css("color", "#000");
	$(".p12e").css("background-color", "#a9a9ae");
	$(".p12e").css("color", "#000");
	$(".p13e").css("background-color", "#a9a9ae");
	$(".p13e").css("color", "#000");
	$(".p12o").css("background-color", "#a9a9ae");
	$(".p12o").css("color", "#000");
	$(".p13o").css("background-color", "#a9a9ae");
	$(".p13o").css("color", "#000");
	
	$(".p16r").css("background-color", "#a9a9ae");
	$(".p16r").css("color", "#000");
	$(".p17r").css("background-color", "#a9a9ae");
	$(".p17r").css("color", "#000");
	$(".p16e").css("background-color", "#a9a9ae");
	$(".p16e").css("color", "#000");
	$(".p17e").css("background-color", "#a9a9ae");
	$(".p17e").css("color", "#000");
	$(".p16o").css("background-color", "#a9a9ae");
	$(".p16o").css("color", "#000");
	$(".p17o").css("background-color", "#a9a9ae");
	$(".p17o").css("color", "#000");
	
	$(".p18r").css("background-color", "#a9a9ae");
	$(".p18r").css("color", "#000");
	$(".p19r").css("background-color", "#a9a9ae");
	$(".p19r").css("color", "#000");
	$(".p18e").css("background-color", "#a9a9ae");
	$(".p18e").css("color", "#000");
	$(".p19e").css("background-color", "#a9a9ae");
	$(".p19e").css("color", "#000");
	$(".p18o").css("background-color", "#a9a9ae");
	$(".p18o").css("color", "#000");
	$(".p19o").css("background-color", "#a9a9ae");
	$(".p19o").css("color", "#000");
	
	$(".p20r").css("background-color", "#a9a9ae");
	$(".p20r").css("color", "#000");
	$(".p21r").css("background-color", "#a9a9ae");
	$(".p21r").css("color", "#000");
	$(".p20e").css("background-color", "#a9a9ae");
	$(".p20e").css("color", "#000");
	$(".p21e").css("background-color", "#a9a9ae");
	$(".p21e").css("color", "#000");
	$(".p20o").css("background-color", "#a9a9ae");
	$(".p20o").css("color", "#000");
	$(".p21o").css("background-color", "#a9a9ae");
	$(".p21o").css("color", "#000");
  });
  
  $(".p16r,.p17r").click(function()
  {
	$("p.nEje9").css("background-color", "#5d2852");
	$(".p16r").css("background-color", "#5d2852");
	$(".p16r").css("color", "#fefefe");
	$(".p17r").css("background-color", "#5d2852");
	$(".p17r").css("color", "#fefefe");
	$(".p16e").css("background-color", "#5d2852");
	$(".p16e").css("color", "#fefefe");
	$(".p17e").css("background-color", "#5d2852");
	$(".p17e").css("color", "#fefefe");
	$(".p16o").css("background-color", "#5d2852");
	$(".p16o").css("color", "#fefefe");
	$(".p17o").css("background-color", "#5d2852");
	$(".p17o").css("color", "#fefefe");
	$(".franja").css("height", "541px");
	
	$("p.nEje1").css("background-color", "#4d4d57");
	$("p.nEje2").css("background-color", "#4d4d57");
	$("p.nEje3").css("background-color", "#4d4d57");
	$("p.nEje4").css("background-color", "#4d4d57");
	$("p.nEje5").css("background-color", "#4d4d57");
	$("p.nEje6").css("background-color", "#4d4d57");
	$("p.nEje7").css("background-color", "#4d4d57");
	$("p.nEje8").css("background-color", "#4d4d57");
	$("p.nEje10").css("background-color", "#4d4d57");
	$("p.nEje11").css("background-color", "#4d4d57");
	
	$(".p0r").css("background-color", "#a9a9ae");
	$(".p0r").css("color", "#000");
	$(".p1r").css("background-color", "#a9a9ae");
	$(".p1r").css("color", "#000");
	$(".p0e").css("background-color", "#a9a9ae");
	$(".p0e").css("color", "#000");
	$(".p1e").css("background-color", "#a9a9ae");
	$(".p1e").css("color", "#000");
	$(".p0o").css("background-color", "#a9a9ae");
	$(".p0o").css("color", "#000");
	$(".p1o").css("background-color", "#a9a9ae");
	$(".p1o").css("color", "#000");
	
	$(".p2r").css("background-color", "#a9a9ae");
	$(".p2r").css("color", "#000");
	$(".p3r").css("background-color", "#a9a9ae");
	$(".p3r").css("color", "#000");
	$(".p2e").css("background-color", "#a9a9ae");
	$(".p2e").css("color", "#000");
	$(".p3e").css("background-color", "#a9a9ae");
	$(".p3e").css("color", "#000");
	$(".p2o").css("background-color", "#a9a9ae");
	$(".p2o").css("color", "#000");
	$(".p3o").css("background-color", "#a9a9ae");
	$(".p3o").css("color", "#000");
	
	$(".p4r").css("background-color", "#a9a9ae");
	$(".p4r").css("color", "#000");
	$(".p5r").css("background-color", "#a9a9ae");
	$(".p5r").css("color", "#000");
	$(".p4e").css("background-color", "#a9a9ae");
	$(".p4e").css("color", "#000");
	$(".p5e").css("background-color", "#a9a9ae");
	$(".p5e").css("color", "#000");
	$(".p4o").css("background-color", "#a9a9ae");
	$(".p4o").css("color", "#000");
	$(".p5o").css("background-color", "#a9a9ae");
	$(".p5o").css("color", "#000");
	
	$(".p6r").css("background-color", "#a9a9ae");
	$(".p6r").css("color", "#000");
	$(".p7r").css("background-color", "#a9a9ae");
	$(".p7r").css("color", "#000");
	$(".p6e").css("background-color", "#a9a9ae");
	$(".p6e").css("color", "#000");
	$(".p7e").css("background-color", "#a9a9ae");
	$(".p7e").css("color", "#000");
	$(".p6o").css("background-color", "#a9a9ae");
	$(".p6o").css("color", "#000");
	$(".p7o").css("background-color", "#a9a9ae");
	$(".p7o").css("color", "#000");
	
	$(".p8r").css("background-color", "#a9a9ae");
	$(".p8r").css("color", "#000");
	$(".p9r").css("background-color", "#a9a9ae");
	$(".p9r").css("color", "#000");
	$(".p8e").css("background-color", "#a9a9ae");
	$(".p8e").css("color", "#000");
	$(".p9e").css("background-color", "#a9a9ae");
	$(".p9e").css("color", "#000");
	$(".p8o").css("background-color", "#a9a9ae");
	$(".p8o").css("color", "#000");
	$(".p9o").css("background-color", "#a9a9ae");
	$(".p9o").css("color", "#000");
	
	$(".p10r").css("background-color", "#a9a9ae");
	$(".p10r").css("color", "#000");
	$(".p11r").css("background-color", "#a9a9ae");
	$(".p11r").css("color", "#000");
	$(".p10e").css("background-color", "#a9a9ae");
	$(".p10e").css("color", "#000");
	$(".p11e").css("background-color", "#a9a9ae");
	$(".p11e").css("color", "#000");
	$(".p10o").css("background-color", "#a9a9ae");
	$(".p10o").css("color", "#000");
	$(".p11o").css("background-color", "#a9a9ae");
	$(".p11o").css("color", "#000");
	
	$(".p12r").css("background-color", "#a9a9ae");
	$(".p12r").css("color", "#000");
	$(".p13r").css("background-color", "#a9a9ae");
	$(".p13r").css("color", "#000");
	$(".p12e").css("background-color", "#a9a9ae");
	$(".p12e").css("color", "#000");
	$(".p13e").css("background-color", "#a9a9ae");
	$(".p13e").css("color", "#000");
	$(".p12o").css("background-color", "#a9a9ae");
	$(".p12o").css("color", "#000");
	$(".p13o").css("background-color", "#a9a9ae");
	$(".p13o").css("color", "#000");
	
	$(".p14r").css("background-color", "#a9a9ae");
	$(".p14r").css("color", "#000");
	$(".p15r").css("background-color", "#a9a9ae");
	$(".p15r").css("color", "#000");
	$(".p14e").css("background-color", "#a9a9ae");
	$(".p14e").css("color", "#000");
	$(".p15e").css("background-color", "#a9a9ae");
	$(".p15e").css("color", "#000");
	$(".p14o").css("background-color", "#a9a9ae");
	$(".p14o").css("color", "#000");
	$(".p15o").css("background-color", "#a9a9ae");
	$(".p15o").css("color", "#000");
	
	$(".p18r").css("background-color", "#a9a9ae");
	$(".p18r").css("color", "#000");
	$(".p19r").css("background-color", "#a9a9ae");
	$(".p19r").css("color", "#000");
	$(".p18e").css("background-color", "#a9a9ae");
	$(".p18e").css("color", "#000");
	$(".p19e").css("background-color", "#a9a9ae");
	$(".p19e").css("color", "#000");
	$(".p18o").css("background-color", "#a9a9ae");
	$(".p18o").css("color", "#000");
	$(".p19o").css("background-color", "#a9a9ae");
	$(".p19o").css("color", "#000");
	
	$(".p20r").css("background-color", "#a9a9ae");
	$(".p20r").css("color", "#000");
	$(".p21r").css("background-color", "#a9a9ae");
	$(".p21r").css("color", "#000");
	$(".p20e").css("background-color", "#a9a9ae");
	$(".p20e").css("color", "#000");
	$(".p21e").css("background-color", "#a9a9ae");
	$(".p21e").css("color", "#000");
	$(".p20o").css("background-color", "#a9a9ae");
	$(".p20o").css("color", "#000");
	$(".p21o").css("background-color", "#a9a9ae");
	$(".p21o").css("color", "#000");
  });
  
  $(".p18r,.p19r").click(function()
  {
	$("p.nEje10").css("background-color", "#5d2852");
	$(".p18r").css("background-color", "#5d2852");
	$(".p18r").css("color", "#fefefe");
	$(".p19r").css("background-color", "#5d2852");
	$(".p19r").css("color", "#fefefe");
	$(".p18e").css("background-color", "#5d2852");
	$(".p18e").css("color", "#fefefe");
	$(".p19e").css("background-color", "#5d2852");
	$(".p19e").css("color", "#fefefe");
	$(".p18o").css("background-color", "#5d2852");
	$(".p18o").css("color", "#fefefe");
	$(".p19o").css("background-color", "#5d2852");
	$(".p19o").css("color", "#fefefe");
	$(".franja").css("height", "594px");
	
	$("p.nEje1").css("background-color", "#4d4d57");
	$("p.nEje2").css("background-color", "#4d4d57");
	$("p.nEje3").css("background-color", "#4d4d57");
	$("p.nEje4").css("background-color", "#4d4d57");
	$("p.nEje5").css("background-color", "#4d4d57");
	$("p.nEje6").css("background-color", "#4d4d57");
	$("p.nEje7").css("background-color", "#4d4d57");
	$("p.nEje8").css("background-color", "#4d4d57");
	$("p.nEje9").css("background-color", "#4d4d57");
	$("p.nEje11").css("background-color", "#4d4d57");
	
	$(".p0r").css("background-color", "#a9a9ae");
	$(".p0r").css("color", "#000");
	$(".p1r").css("background-color", "#a9a9ae");
	$(".p1r").css("color", "#000");
	$(".p0e").css("background-color", "#a9a9ae");
	$(".p0e").css("color", "#000");
	$(".p1e").css("background-color", "#a9a9ae");
	$(".p1e").css("color", "#000");
	$(".p0o").css("background-color", "#a9a9ae");
	$(".p0o").css("color", "#000");
	$(".p1o").css("background-color", "#a9a9ae");
	$(".p1o").css("color", "#000");
	
	$(".p2r").css("background-color", "#a9a9ae");
	$(".p2r").css("color", "#000");
	$(".p3r").css("background-color", "#a9a9ae");
	$(".p3r").css("color", "#000");
	$(".p2e").css("background-color", "#a9a9ae");
	$(".p2e").css("color", "#000");
	$(".p3e").css("background-color", "#a9a9ae");
	$(".p3e").css("color", "#000");
	$(".p2o").css("background-color", "#a9a9ae");
	$(".p2o").css("color", "#000");
	$(".p3o").css("background-color", "#a9a9ae");
	$(".p3o").css("color", "#000");
	
	$(".p4r").css("background-color", "#a9a9ae");
	$(".p4r").css("color", "#000");
	$(".p5r").css("background-color", "#a9a9ae");
	$(".p5r").css("color", "#000");
	$(".p4e").css("background-color", "#a9a9ae");
	$(".p4e").css("color", "#000");
	$(".p5e").css("background-color", "#a9a9ae");
	$(".p5e").css("color", "#000");
	$(".p4o").css("background-color", "#a9a9ae");
	$(".p4o").css("color", "#000");
	$(".p5o").css("background-color", "#a9a9ae");
	$(".p5o").css("color", "#000");
	
	$(".p6r").css("background-color", "#a9a9ae");
	$(".p6r").css("color", "#000");
	$(".p7r").css("background-color", "#a9a9ae");
	$(".p7r").css("color", "#000");
	$(".p6e").css("background-color", "#a9a9ae");
	$(".p6e").css("color", "#000");
	$(".p7e").css("background-color", "#a9a9ae");
	$(".p7e").css("color", "#000");
	$(".p6o").css("background-color", "#a9a9ae");
	$(".p6o").css("color", "#000");
	$(".p7o").css("background-color", "#a9a9ae");
	$(".p7o").css("color", "#000");
	
	$(".p8r").css("background-color", "#a9a9ae");
	$(".p8r").css("color", "#000");
	$(".p9r").css("background-color", "#a9a9ae");
	$(".p9r").css("color", "#000");
	$(".p8e").css("background-color", "#a9a9ae");
	$(".p8e").css("color", "#000");
	$(".p9e").css("background-color", "#a9a9ae");
	$(".p9e").css("color", "#000");
	$(".p8o").css("background-color", "#a9a9ae");
	$(".p8o").css("color", "#000");
	$(".p9o").css("background-color", "#a9a9ae");
	$(".p9o").css("color", "#000");
	
	$(".p10r").css("background-color", "#a9a9ae");
	$(".p10r").css("color", "#000");
	$(".p11r").css("background-color", "#a9a9ae");
	$(".p11r").css("color", "#000");
	$(".p10e").css("background-color", "#a9a9ae");
	$(".p10e").css("color", "#000");
	$(".p11e").css("background-color", "#a9a9ae");
	$(".p11e").css("color", "#000");
	$(".p10o").css("background-color", "#a9a9ae");
	$(".p10o").css("color", "#000");
	$(".p11o").css("background-color", "#a9a9ae");
	$(".p11o").css("color", "#000");
	
	$(".p12r").css("background-color", "#a9a9ae");
	$(".p12r").css("color", "#000");
	$(".p13r").css("background-color", "#a9a9ae");
	$(".p13r").css("color", "#000");
	$(".p12e").css("background-color", "#a9a9ae");
	$(".p12e").css("color", "#000");
	$(".p13e").css("background-color", "#a9a9ae");
	$(".p13e").css("color", "#000");
	$(".p12o").css("background-color", "#a9a9ae");
	$(".p12o").css("color", "#000");
	$(".p13o").css("background-color", "#a9a9ae");
	$(".p13o").css("color", "#000");
	
	$(".p14r").css("background-color", "#a9a9ae");
	$(".p14r").css("color", "#000");
	$(".p15r").css("background-color", "#a9a9ae");
	$(".p15r").css("color", "#000");
	$(".p14e").css("background-color", "#a9a9ae");
	$(".p14e").css("color", "#000");
	$(".p15e").css("background-color", "#a9a9ae");
	$(".p15e").css("color", "#000");
	$(".p14o").css("background-color", "#a9a9ae");
	$(".p14o").css("color", "#000");
	$(".p15o").css("background-color", "#a9a9ae");
	$(".p15o").css("color", "#000");
	
	$(".p16r").css("background-color", "#a9a9ae");
	$(".p16r").css("color", "#000");
	$(".p17r").css("background-color", "#a9a9ae");
	$(".p17r").css("color", "#000");
	$(".p16e").css("background-color", "#a9a9ae");
	$(".p16e").css("color", "#000");
	$(".p17e").css("background-color", "#a9a9ae");
	$(".p17e").css("color", "#000");
	$(".p16o").css("background-color", "#a9a9ae");
	$(".p16o").css("color", "#000");
	$(".p17o").css("background-color", "#a9a9ae");
	$(".p17o").css("color", "#000");
	
	$(".p20r").css("background-color", "#a9a9ae");
	$(".p20r").css("color", "#000");
	$(".p21r").css("background-color", "#a9a9ae");
	$(".p21r").css("color", "#000");
	$(".p20e").css("background-color", "#a9a9ae");
	$(".p20e").css("color", "#000");
	$(".p21e").css("background-color", "#a9a9ae");
	$(".p21e").css("color", "#000");
	$(".p20o").css("background-color", "#a9a9ae");
	$(".p20o").css("color", "#000");
	$(".p21o").css("background-color", "#a9a9ae");
	$(".p21o").css("color", "#000");
  });
  
    $(".p20r,.p21r").click(function()
  {
	$("p.nEje11").css("background-color", "#5d2852");
	$(".p20r").css("background-color", "#5d2852");
	$(".p20r").css("color", "#fefefe");
	$(".p21r").css("background-color", "#5d2852");
	$(".p21r").css("color", "#fefefe");
	$(".p20e").css("background-color", "#5d2852");
	$(".p20e").css("color", "#fefefe");
	$(".p21e").css("background-color", "#5d2852");
	$(".p21e").css("color", "#fefefe");
	$(".p20o").css("background-color", "#5d2852");
	$(".p20o").css("color", "#fefefe");
	$(".p21o").css("background-color", "#5d2852");
	$(".p21o").css("color", "#fefefe");
	$(".franja").css("height", "647px");
	
	$("p.nEje1").css("background-color", "#4d4d57");
	$("p.nEje2").css("background-color", "#4d4d57");
	$("p.nEje3").css("background-color", "#4d4d57");
	$("p.nEje4").css("background-color", "#4d4d57");
	$("p.nEje5").css("background-color", "#4d4d57");
	$("p.nEje6").css("background-color", "#4d4d57");
	$("p.nEje7").css("background-color", "#4d4d57");
	$("p.nEje8").css("background-color", "#4d4d57");
	$("p.nEje9").css("background-color", "#4d4d57");
	$("p.nEje10").css("background-color", "#4d4d57");
	
	$(".p0r").css("background-color", "#a9a9ae");
	$(".p0r").css("color", "#000");
	$(".p1r").css("background-color", "#a9a9ae");
	$(".p1r").css("color", "#000");
	$(".p0e").css("background-color", "#a9a9ae");
	$(".p0e").css("color", "#000");
	$(".p1e").css("background-color", "#a9a9ae");
	$(".p1e").css("color", "#000");
	$(".p0o").css("background-color", "#a9a9ae");
	$(".p0o").css("color", "#000");
	$(".p1o").css("background-color", "#a9a9ae");
	$(".p1o").css("color", "#000");
	
	$(".p2r").css("background-color", "#a9a9ae");
	$(".p2r").css("color", "#000");
	$(".p3r").css("background-color", "#a9a9ae");
	$(".p3r").css("color", "#000");
	$(".p2e").css("background-color", "#a9a9ae");
	$(".p2e").css("color", "#000");
	$(".p3e").css("background-color", "#a9a9ae");
	$(".p3e").css("color", "#000");
	$(".p2o").css("background-color", "#a9a9ae");
	$(".p2o").css("color", "#000");
	$(".p3o").css("background-color", "#a9a9ae");
	$(".p3o").css("color", "#000");
	
	$(".p4r").css("background-color", "#a9a9ae");
	$(".p4r").css("color", "#000");
	$(".p5r").css("background-color", "#a9a9ae");
	$(".p5r").css("color", "#000");
	$(".p4e").css("background-color", "#a9a9ae");
	$(".p4e").css("color", "#000");
	$(".p5e").css("background-color", "#a9a9ae");
	$(".p5e").css("color", "#000");
	$(".p4o").css("background-color", "#a9a9ae");
	$(".p4o").css("color", "#000");
	$(".p5o").css("background-color", "#a9a9ae");
	$(".p5o").css("color", "#000");
	
	$(".p6r").css("background-color", "#a9a9ae");
	$(".p6r").css("color", "#000");
	$(".p7r").css("background-color", "#a9a9ae");
	$(".p7r").css("color", "#000");
	$(".p6e").css("background-color", "#a9a9ae");
	$(".p6e").css("color", "#000");
	$(".p7e").css("background-color", "#a9a9ae");
	$(".p7e").css("color", "#000");
	$(".p6o").css("background-color", "#a9a9ae");
	$(".p6o").css("color", "#000");
	$(".p7o").css("background-color", "#a9a9ae");
	$(".p7o").css("color", "#000");
	
	$(".p8r").css("background-color", "#a9a9ae");
	$(".p8r").css("color", "#000");
	$(".p9r").css("background-color", "#a9a9ae");
	$(".p9r").css("color", "#000");
	$(".p8e").css("background-color", "#a9a9ae");
	$(".p8e").css("color", "#000");
	$(".p9e").css("background-color", "#a9a9ae");
	$(".p9e").css("color", "#000");
	$(".p8o").css("background-color", "#a9a9ae");
	$(".p8o").css("color", "#000");
	$(".p9o").css("background-color", "#a9a9ae");
	$(".p9o").css("color", "#000");
	
	$(".p10r").css("background-color", "#a9a9ae");
	$(".p10r").css("color", "#000");
	$(".p11r").css("background-color", "#a9a9ae");
	$(".p11r").css("color", "#000");
	$(".p10e").css("background-color", "#a9a9ae");
	$(".p10e").css("color", "#000");
	$(".p11e").css("background-color", "#a9a9ae");
	$(".p11e").css("color", "#000");
	$(".p10o").css("background-color", "#a9a9ae");
	$(".p10o").css("color", "#000");
	$(".p11o").css("background-color", "#a9a9ae");
	$(".p11o").css("color", "#000");
	
	$(".p12r").css("background-color", "#a9a9ae");
	$(".p12r").css("color", "#000");
	$(".p13r").css("background-color", "#a9a9ae");
	$(".p13r").css("color", "#000");
	$(".p12e").css("background-color", "#a9a9ae");
	$(".p12e").css("color", "#000");
	$(".p13e").css("background-color", "#a9a9ae");
	$(".p13e").css("color", "#000");
	$(".p12o").css("background-color", "#a9a9ae");
	$(".p12o").css("color", "#000");
	$(".p13o").css("background-color", "#a9a9ae");
	$(".p13o").css("color", "#000");
	
	$(".p14r").css("background-color", "#a9a9ae");
	$(".p14r").css("color", "#000");
	$(".p15r").css("background-color", "#a9a9ae");
	$(".p15r").css("color", "#000");
	$(".p14e").css("background-color", "#a9a9ae");
	$(".p14e").css("color", "#000");
	$(".p15e").css("background-color", "#a9a9ae");
	$(".p15e").css("color", "#000");
	$(".p14o").css("background-color", "#a9a9ae");
	$(".p14o").css("color", "#000");
	$(".p15o").css("background-color", "#a9a9ae");
	$(".p15o").css("color", "#000");
	
	$(".p16r").css("background-color", "#a9a9ae");
	$(".p16r").css("color", "#000");
	$(".p17r").css("background-color", "#a9a9ae");
	$(".p17r").css("color", "#000");
	$(".p16e").css("background-color", "#a9a9ae");
	$(".p16e").css("color", "#000");
	$(".p17e").css("background-color", "#a9a9ae");
	$(".p17e").css("color", "#000");
	$(".p16o").css("background-color", "#a9a9ae");
	$(".p16o").css("color", "#000");
	$(".p17o").css("background-color", "#a9a9ae");
	$(".p17o").css("color", "#000");
	
	$(".p18r").css("background-color", "#a9a9ae");
	$(".p18r").css("color", "#000");
	$(".p19r").css("background-color", "#a9a9ae");
	$(".p19r").css("color", "#000");
	$(".p18e").css("background-color", "#a9a9ae");
	$(".p18e").css("color", "#000");
	$(".p19e").css("background-color", "#a9a9ae");
	$(".p19e").css("color", "#000");
	$(".p18o").css("background-color", "#a9a9ae");
	$(".p18o").css("color", "#000");
	$(".p19o").css("background-color", "#a9a9ae");
	$(".p19o").css("color", "#000");
  });
});
</script>